stages:
  - deploy

workflow:
  rules:
    - changes:
        - "*"
      when: never
    - when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always

helm-deploy:
  stage: deploy
  image: bitnami/kubectl:1.21.10
  script:
    - kubectl apply --namespace cron -f ./infra --recursive
    - kubectl apply --namespace cron -f ./storage --recursive
    - kubectl apply --namespace cron -f ./cronjob --recursive
