stages:
  - deploy

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE != "web"'
      changes:
        - "*"
      when: never
    - when: always

helm-deploy:
  stage: deploy
  image: bitnami/kubectl:1.21.10
  script:
    - kubectl apply --namespace kube-system -f ./infra --recursive
    - kubectl apply --namespace cron -f ./storage --recursive
    - kubectl apply --namespace cron -f ./cronjob --recursive
