stages:
  - deploy

workflow:
  rules:
    - changes:
        - "*"
      when: never
    - when: always

helm-deploy:
  stage: deploy
  image: bitnami/kubectl:1.21.10
  script:
    - kubectl apply --namespace cron -f ./cronjob --recursive
