apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-dev-copy
  namespace: cron
spec:
  schedule: "30 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: s3-dev-copy
              image: docker.io/rclone/rclone
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: rclone-config
                  mountPath: /config/rclone/rclone.conf
                  subPath: rclone.conf
              command:
                - sh
                - -c
                - rclone --verbose sync --checksum switch:envidat-staging switch:envidat-dev
          restartPolicy: OnFailure
          volumes:
            - name: rclone-config
              secret:
                secretName: rclone-config
