apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-data-nfs-pvc
  namespace: cron
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 9Ti
  volumeName: drone-data-nfs-pv
