apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: envidat-nfs-pvc
  namespace: cron
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Ti
  volumeName: envidat-nfs-pv
