apiVersion: v1
kind: PersistentVolume
metadata:
  name: envidat-nfs-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.30.1.245
    path: "/vol_data"
