apiVersion: batch/v1
kind: CronJob
metadata:
  name: ckan-nasa-gcmd
  namespace: cron
spec:
  schedule: "0 3 * * 1,4"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ckan-nasa-gcmd
              image: registry.envidat.ch/envidat/nasa-gcmd:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: LOG_LEVEL
                  value: DEBUG
                - name: AWS_BUCKET_NAME
                  value: nasa
                - name: CKAN_HOST
                  value: https://www.envidat.ch
              envFrom:
                - secretRef:
                    name: switch-s3-py-env
          restartPolicy: OnFailure
