apiVersion: batch/v1
kind: CronJob
metadata:
  name: nasa-gcmd
  namespace: cron
spec:
  schedule: "15 3 * * 1,4"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/log-format: python
        spec:
          containers:
            - name: nasa-gcmd
              image: registry.envidat.ch/envidat/nasa-gcmd:latest
              imagePullPolicy: Always
              env:
                - name: LOG_LEVEL
                  value: DEBUG
                - name: API_URL
                  value: https://www.envidat.ch
              envFrom:
                - secretRef:
                    name: switch-s3-py-env
          restartPolicy: OnFailure
