apiVersion: batch/v1
kind: CronJob
metadata:
  name: opendataswiss-dcap-ap
  namespace: cron
spec:
  schedule: "30 3 * * 1,4"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: opendataswiss-dcap-ap
              image: registry.envidat.ch/envidat/opendataswiss:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: LOG_LEVEL
                  value: DEBUG
                - name: API_URL
                  value: https://www.envidat.ch
              envFrom:
                - secretRef:
                    name: switch-s3-creds
          restartPolicy: OnFailure
